this is for exceptions in pythin

